=== QuasarRay/CPGSchema/JsonSchema/schemas/bundle.meta.schema.json
{
  "type": "object",
  "properties": {
    "$schema": {
      "const": "https://quasarray.github.io/CPGSchema/dialect/1"
    },
    "$id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "cpg:builder": {
      "type": "object",
      "properties": {
        "domainShortName": {
          "type": "string"
        },
        "basePackage": {
          "type": "string"
        },
        "additionalTraversalsPackages": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "domainShortName",
        "basePackage",
        "additionalTraversalsPackages"
      ],
      "additionalProperties": false
    },
    "cpg:composition": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "cpg:modules": {
      "type": "array",
      "items": {
        "$ref": "https://quasarray.github.io/CPGSchema/meta/module/1"
      }
    },
    "cpg:propertyDefaults": {
      "type": "object",
      "additionalProperties": {
        "$ref": "https://quasarray.github.io/CPGSchema/meta/module/1#/$defs/scalar"
      }
    }
  },
  "required": [
    "cpg:builder"
  ],
  "additionalProperties": false,
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://quasarray.github.io/CPGSchema/meta/bundle/1",
  "oneOf": [
    {
      "required": [
        "cpg:composition"
      ],
      "not": {
        "required": [
          "cpg:modules"
        ]
      }
    },
    {
      "required": [
        "cpg:modules"
      ],
      "not": {
        "required": [
          "cpg:composition"
        ]
      }
    }
  ]
}

=== QuasarRay/CPGSchema/JsonSchema/src/CpgSchema/schema.json
{
  "$schema": "https://quasarray.github.io/CPGSchema/dialect/1",
  "$id": "https://quasarray.github.io/CPGSchema/modules/CpgSchema/1",
  "title": "CpgSchema",
  "cpg:builder": {
    "domainShortName": "Cpg",
    "basePackage": "io.shiftleft.codepropertygraph.generated",
    "additionalTraversalsPackages": [
      "io.shiftleft"
    ]
  },
  "cpg:composition": [
    "Base",
    "FileSystem",
    "Namespace",
    "Operators",
    "Configuration",
    "MetaData",
    "Type",
    "Method",
    "Ast",
    "CallGraph",
    "Cfg",
    "Dominators",
    "Pdg",
    "Shortcuts",
    "Comment",
    "Tags",
    "Binding",
    "Annotation",
    "Finding",
    "Hidden",
    "ProtoSerialize"
  ],
  "cpg:propertyDefaults": {
    "String": {
      "type": "String",
      "value": "<empty>"
    },
    "Boolean": {
      "type": "Boolean",
      "value": false
    },
    "Byte": {
      "type": "Byte",
      "value": "-1"
    },
    "Short": {
      "type": "Short",
      "value": "-1"
    },
    "Int": {
      "type": "Int",
      "value": "-1"
    },
    "Long": {
      "type": "Long",
      "value": "-1"
    },
    "Float": {
      "type": "Float",
      "bits": "00000000"
    },
    "Double": {
      "type": "Double",
      "bits": "0000000000000000"
    },
    "Char": {
      "type": "Char",
      "value": 63
    }
  }
}
